# Project Properties
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# Project Information
project.group=com.lukester814
project.version=2.0.0
project.name=hi-alch-bot

# Java Configuration
java.sourceCompatibility=1.8
java.targetCompatibility=1.8
